name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.25
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - run: make build
      - run: make test
